// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GroupBandwidthsColumns holds the columns for the "group_bandwidths" table.
	GroupBandwidthsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gbw_download_speed", Type: field.TypeInt},
		{Name: "gbw_upload_speed", Type: field.TypeInt},
		{Name: "gbw_created_at", Type: field.TypeTime, Nullable: true},
	}
	// GroupBandwidthsTable holds the schema information for the "group_bandwidths" table.
	GroupBandwidthsTable = &schema.Table{
		Name:       "group_bandwidths",
		Columns:    GroupBandwidthsColumns,
		PrimaryKey: []*schema.Column{GroupBandwidthsColumns[0]},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "g_name", Type: field.TypeString},
		{Name: "g_is_int_org", Type: field.TypeBool, Default: true},
		{Name: "g_is_super_admin", Type: field.TypeBool, Default: false},
		{Name: "g_created_at", Type: field.TypeTime, Nullable: true},
		{Name: "group_bandwidth_groups", Type: field.TypeInt, Nullable: true},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groups_group_bandwidths_groups",
				Columns:    []*schema.Column{GroupsColumns[5]},
				RefColumns: []*schema.Column{GroupBandwidthsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OnlineSessionsColumns holds the columns for the "online_sessions" table.
	OnlineSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip_address", Type: field.TypeString, Size: 15},
		{Name: "u_pid", Type: field.TypeString, Unique: true, Size: 13},
	}
	// OnlineSessionsTable holds the schema information for the "online_sessions" table.
	OnlineSessionsTable = &schema.Table{
		Name:       "online_sessions",
		Columns:    OnlineSessionsColumns,
		PrimaryKey: []*schema.Column{OnlineSessionsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "u_pid", Type: field.TypeString, Unique: true, Size: 13},
		{Name: "u_orgid", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "u_first_name", Type: field.TypeString, Size: 50},
		{Name: "u_last_name", Type: field.TypeString, Size: 50},
		{Name: "u_is_active", Type: field.TypeBool, Default: false},
		{Name: "u_created_at", Type: field.TypeTime, Nullable: true},
		{Name: "u_password_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "u_expired_at", Type: field.TypeTime, Nullable: true},
		{Name: "groups_users", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_groups_users",
				Columns:    []*schema.Column{UsersColumns[9]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GroupBandwidthsTable,
		GroupsTable,
		OnlineSessionsTable,
		UsersTable,
	}
)

func init() {
	GroupsTable.ForeignKeys[0].RefTable = GroupBandwidthsTable
	UsersTable.ForeignKeys[0].RefTable = GroupsTable
}
