// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/mrz-identity-management/ent/groupbandwidth"
	"github.com/mrzack99s/mrz-identity-management/ent/groups"
	"github.com/mrzack99s/mrz-identity-management/ent/predicate"
)

// GroupBandwidthQuery is the builder for querying GroupBandwidth entities.
type GroupBandwidthQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GroupBandwidth
	// eager-loading edges.
	withGroups *GroupsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupBandwidthQuery builder.
func (gbq *GroupBandwidthQuery) Where(ps ...predicate.GroupBandwidth) *GroupBandwidthQuery {
	gbq.predicates = append(gbq.predicates, ps...)
	return gbq
}

// Limit adds a limit step to the query.
func (gbq *GroupBandwidthQuery) Limit(limit int) *GroupBandwidthQuery {
	gbq.limit = &limit
	return gbq
}

// Offset adds an offset step to the query.
func (gbq *GroupBandwidthQuery) Offset(offset int) *GroupBandwidthQuery {
	gbq.offset = &offset
	return gbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gbq *GroupBandwidthQuery) Unique(unique bool) *GroupBandwidthQuery {
	gbq.unique = &unique
	return gbq
}

// Order adds an order step to the query.
func (gbq *GroupBandwidthQuery) Order(o ...OrderFunc) *GroupBandwidthQuery {
	gbq.order = append(gbq.order, o...)
	return gbq
}

// QueryGroups chains the current query on the "groups" edge.
func (gbq *GroupBandwidthQuery) QueryGroups() *GroupsQuery {
	query := &GroupsQuery{config: gbq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbandwidth.Table, groupbandwidth.FieldID, selector),
			sqlgraph.To(groups.Table, groups.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, groupbandwidth.GroupsTable, groupbandwidth.GroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(gbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupBandwidth entity from the query.
// Returns a *NotFoundError when no GroupBandwidth was found.
func (gbq *GroupBandwidthQuery) First(ctx context.Context) (*GroupBandwidth, error) {
	nodes, err := gbq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupbandwidth.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) FirstX(ctx context.Context) *GroupBandwidth {
	node, err := gbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupBandwidth ID from the query.
// Returns a *NotFoundError when no GroupBandwidth ID was found.
func (gbq *GroupBandwidthQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gbq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupbandwidth.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) FirstIDX(ctx context.Context) int {
	id, err := gbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupBandwidth entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one GroupBandwidth entity is not found.
// Returns a *NotFoundError when no GroupBandwidth entities are found.
func (gbq *GroupBandwidthQuery) Only(ctx context.Context) (*GroupBandwidth, error) {
	nodes, err := gbq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupbandwidth.Label}
	default:
		return nil, &NotSingularError{groupbandwidth.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) OnlyX(ctx context.Context) *GroupBandwidth {
	node, err := gbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupBandwidth ID in the query.
// Returns a *NotSingularError when exactly one GroupBandwidth ID is not found.
// Returns a *NotFoundError when no entities are found.
func (gbq *GroupBandwidthQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gbq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = &NotSingularError{groupbandwidth.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) OnlyIDX(ctx context.Context) int {
	id, err := gbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupBandwidths.
func (gbq *GroupBandwidthQuery) All(ctx context.Context) ([]*GroupBandwidth, error) {
	if err := gbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gbq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) AllX(ctx context.Context) []*GroupBandwidth {
	nodes, err := gbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupBandwidth IDs.
func (gbq *GroupBandwidthQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := gbq.Select(groupbandwidth.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) IDsX(ctx context.Context) []int {
	ids, err := gbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gbq *GroupBandwidthQuery) Count(ctx context.Context) (int, error) {
	if err := gbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gbq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) CountX(ctx context.Context) int {
	count, err := gbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gbq *GroupBandwidthQuery) Exist(ctx context.Context) (bool, error) {
	if err := gbq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gbq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gbq *GroupBandwidthQuery) ExistX(ctx context.Context) bool {
	exist, err := gbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupBandwidthQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gbq *GroupBandwidthQuery) Clone() *GroupBandwidthQuery {
	if gbq == nil {
		return nil
	}
	return &GroupBandwidthQuery{
		config:     gbq.config,
		limit:      gbq.limit,
		offset:     gbq.offset,
		order:      append([]OrderFunc{}, gbq.order...),
		predicates: append([]predicate.GroupBandwidth{}, gbq.predicates...),
		withGroups: gbq.withGroups.Clone(),
		// clone intermediate query.
		sql:  gbq.sql.Clone(),
		path: gbq.path,
	}
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (gbq *GroupBandwidthQuery) WithGroups(opts ...func(*GroupsQuery)) *GroupBandwidthQuery {
	query := &GroupsQuery{config: gbq.config}
	for _, opt := range opts {
		opt(query)
	}
	gbq.withGroups = query
	return gbq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GbwDownloadSpeed int `json:"gbw_download_speed,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupBandwidth.Query().
//		GroupBy(groupbandwidth.FieldGbwDownloadSpeed).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gbq *GroupBandwidthQuery) GroupBy(field string, fields ...string) *GroupBandwidthGroupBy {
	group := &GroupBandwidthGroupBy{config: gbq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gbq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GbwDownloadSpeed int `json:"gbw_download_speed,omitempty"`
//	}
//
//	client.GroupBandwidth.Query().
//		Select(groupbandwidth.FieldGbwDownloadSpeed).
//		Scan(ctx, &v)
//
func (gbq *GroupBandwidthQuery) Select(fields ...string) *GroupBandwidthSelect {
	gbq.fields = append(gbq.fields, fields...)
	return &GroupBandwidthSelect{GroupBandwidthQuery: gbq}
}

func (gbq *GroupBandwidthQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gbq.fields {
		if !groupbandwidth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gbq.path != nil {
		prev, err := gbq.path(ctx)
		if err != nil {
			return err
		}
		gbq.sql = prev
	}
	return nil
}

func (gbq *GroupBandwidthQuery) sqlAll(ctx context.Context) ([]*GroupBandwidth, error) {
	var (
		nodes       = []*GroupBandwidth{}
		_spec       = gbq.querySpec()
		loadedTypes = [1]bool{
			gbq.withGroups != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &GroupBandwidth{config: gbq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, gbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := gbq.withGroups; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*GroupBandwidth)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Groups = []*Groups{}
		}
		query.withFKs = true
		query.Where(predicate.Groups(func(s *sql.Selector) {
			s.Where(sql.InValues(groupbandwidth.GroupsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.group_bandwidth_groups
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "group_bandwidth_groups" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "group_bandwidth_groups" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Groups = append(node.Edges.Groups, n)
		}
	}

	return nodes, nil
}

func (gbq *GroupBandwidthQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gbq.querySpec()
	return sqlgraph.CountNodes(ctx, gbq.driver, _spec)
}

func (gbq *GroupBandwidthQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gbq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gbq *GroupBandwidthQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groupbandwidth.Table,
			Columns: groupbandwidth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupbandwidth.FieldID,
			},
		},
		From:   gbq.sql,
		Unique: true,
	}
	if unique := gbq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gbq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupbandwidth.FieldID)
		for i := range fields {
			if fields[i] != groupbandwidth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gbq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gbq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gbq *GroupBandwidthQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gbq.driver.Dialect())
	t1 := builder.Table(groupbandwidth.Table)
	columns := gbq.fields
	if len(columns) == 0 {
		columns = groupbandwidth.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gbq.sql != nil {
		selector = gbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range gbq.predicates {
		p(selector)
	}
	for _, p := range gbq.order {
		p(selector)
	}
	if offset := gbq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gbq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroupBandwidthGroupBy is the group-by builder for GroupBandwidth entities.
type GroupBandwidthGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gbgb *GroupBandwidthGroupBy) Aggregate(fns ...AggregateFunc) *GroupBandwidthGroupBy {
	gbgb.fns = append(gbgb.fns, fns...)
	return gbgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gbgb *GroupBandwidthGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gbgb.path(ctx)
	if err != nil {
		return err
	}
	gbgb.sql = query
	return gbgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := gbgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(gbgb.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := gbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) StringsX(ctx context.Context) []string {
	v, err := gbgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gbgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) StringX(ctx context.Context) string {
	v, err := gbgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(gbgb.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := gbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) IntsX(ctx context.Context) []int {
	v, err := gbgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gbgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) IntX(ctx context.Context) int {
	v, err := gbgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(gbgb.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := gbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := gbgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gbgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) Float64X(ctx context.Context) float64 {
	v, err := gbgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(gbgb.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := gbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := gbgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gbgb *GroupBandwidthGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gbgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gbgb *GroupBandwidthGroupBy) BoolX(ctx context.Context) bool {
	v, err := gbgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gbgb *GroupBandwidthGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gbgb.fields {
		if !groupbandwidth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gbgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gbgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gbgb *GroupBandwidthGroupBy) sqlQuery() *sql.Selector {
	selector := gbgb.sql.Select()
	aggregation := make([]string, 0, len(gbgb.fns))
	for _, fn := range gbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gbgb.fields)+len(gbgb.fns))
		for _, f := range gbgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gbgb.fields...)...)
}

// GroupBandwidthSelect is the builder for selecting fields of GroupBandwidth entities.
type GroupBandwidthSelect struct {
	*GroupBandwidthQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gbs *GroupBandwidthSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gbs.prepareQuery(ctx); err != nil {
		return err
	}
	gbs.sql = gbs.GroupBandwidthQuery.sqlQuery(ctx)
	return gbs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) ScanX(ctx context.Context, v interface{}) {
	if err := gbs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Strings(ctx context.Context) ([]string, error) {
	if len(gbs.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := gbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) StringsX(ctx context.Context) []string {
	v, err := gbs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gbs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) StringX(ctx context.Context) string {
	v, err := gbs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Ints(ctx context.Context) ([]int, error) {
	if len(gbs.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := gbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) IntsX(ctx context.Context) []int {
	v, err := gbs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gbs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) IntX(ctx context.Context) int {
	v, err := gbs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(gbs.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := gbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) Float64sX(ctx context.Context) []float64 {
	v, err := gbs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gbs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) Float64X(ctx context.Context) float64 {
	v, err := gbs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(gbs.fields) > 1 {
		return nil, errors.New("ent: GroupBandwidthSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := gbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) BoolsX(ctx context.Context) []bool {
	v, err := gbs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (gbs *GroupBandwidthSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gbs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupbandwidth.Label}
	default:
		err = fmt.Errorf("ent: GroupBandwidthSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gbs *GroupBandwidthSelect) BoolX(ctx context.Context) bool {
	v, err := gbs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gbs *GroupBandwidthSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gbs.sql.Query()
	if err := gbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
