// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/mrz-identity-management/ent/onlinesession"
	"github.com/mrzack99s/mrz-identity-management/ent/predicate"
)

// OnlineSessionUpdate is the builder for updating OnlineSession entities.
type OnlineSessionUpdate struct {
	config
	hooks    []Hook
	mutation *OnlineSessionMutation
}

// Where appends a list predicates to the OnlineSessionUpdate builder.
func (osu *OnlineSessionUpdate) Where(ps ...predicate.OnlineSession) *OnlineSessionUpdate {
	osu.mutation.Where(ps...)
	return osu
}

// SetIPAddress sets the "ip_address" field.
func (osu *OnlineSessionUpdate) SetIPAddress(s string) *OnlineSessionUpdate {
	osu.mutation.SetIPAddress(s)
	return osu
}

// SetUPid sets the "u_pid" field.
func (osu *OnlineSessionUpdate) SetUPid(s string) *OnlineSessionUpdate {
	osu.mutation.SetUPid(s)
	return osu
}

// Mutation returns the OnlineSessionMutation object of the builder.
func (osu *OnlineSessionUpdate) Mutation() *OnlineSessionMutation {
	return osu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (osu *OnlineSessionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(osu.hooks) == 0 {
		if err = osu.check(); err != nil {
			return 0, err
		}
		affected, err = osu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OnlineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = osu.check(); err != nil {
				return 0, err
			}
			osu.mutation = mutation
			affected, err = osu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(osu.hooks) - 1; i >= 0; i-- {
			if osu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = osu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, osu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (osu *OnlineSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := osu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (osu *OnlineSessionUpdate) Exec(ctx context.Context) error {
	_, err := osu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (osu *OnlineSessionUpdate) ExecX(ctx context.Context) {
	if err := osu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (osu *OnlineSessionUpdate) check() error {
	if v, ok := osu.mutation.IPAddress(); ok {
		if err := onlinesession.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf("ent: validator failed for field \"ip_address\": %w", err)}
		}
	}
	if v, ok := osu.mutation.UPid(); ok {
		if err := onlinesession.UPidValidator(v); err != nil {
			return &ValidationError{Name: "u_pid", err: fmt.Errorf("ent: validator failed for field \"u_pid\": %w", err)}
		}
	}
	return nil
}

func (osu *OnlineSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   onlinesession.Table,
			Columns: onlinesession.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: onlinesession.FieldID,
			},
		},
	}
	if ps := osu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := osu.mutation.IPAddress(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: onlinesession.FieldIPAddress,
		})
	}
	if value, ok := osu.mutation.UPid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: onlinesession.FieldUPid,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, osu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onlinesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// OnlineSessionUpdateOne is the builder for updating a single OnlineSession entity.
type OnlineSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OnlineSessionMutation
}

// SetIPAddress sets the "ip_address" field.
func (osuo *OnlineSessionUpdateOne) SetIPAddress(s string) *OnlineSessionUpdateOne {
	osuo.mutation.SetIPAddress(s)
	return osuo
}

// SetUPid sets the "u_pid" field.
func (osuo *OnlineSessionUpdateOne) SetUPid(s string) *OnlineSessionUpdateOne {
	osuo.mutation.SetUPid(s)
	return osuo
}

// Mutation returns the OnlineSessionMutation object of the builder.
func (osuo *OnlineSessionUpdateOne) Mutation() *OnlineSessionMutation {
	return osuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (osuo *OnlineSessionUpdateOne) Select(field string, fields ...string) *OnlineSessionUpdateOne {
	osuo.fields = append([]string{field}, fields...)
	return osuo
}

// Save executes the query and returns the updated OnlineSession entity.
func (osuo *OnlineSessionUpdateOne) Save(ctx context.Context) (*OnlineSession, error) {
	var (
		err  error
		node *OnlineSession
	)
	if len(osuo.hooks) == 0 {
		if err = osuo.check(); err != nil {
			return nil, err
		}
		node, err = osuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OnlineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = osuo.check(); err != nil {
				return nil, err
			}
			osuo.mutation = mutation
			node, err = osuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(osuo.hooks) - 1; i >= 0; i-- {
			if osuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = osuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, osuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (osuo *OnlineSessionUpdateOne) SaveX(ctx context.Context) *OnlineSession {
	node, err := osuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (osuo *OnlineSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := osuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (osuo *OnlineSessionUpdateOne) ExecX(ctx context.Context) {
	if err := osuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (osuo *OnlineSessionUpdateOne) check() error {
	if v, ok := osuo.mutation.IPAddress(); ok {
		if err := onlinesession.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf("ent: validator failed for field \"ip_address\": %w", err)}
		}
	}
	if v, ok := osuo.mutation.UPid(); ok {
		if err := onlinesession.UPidValidator(v); err != nil {
			return &ValidationError{Name: "u_pid", err: fmt.Errorf("ent: validator failed for field \"u_pid\": %w", err)}
		}
	}
	return nil
}

func (osuo *OnlineSessionUpdateOne) sqlSave(ctx context.Context) (_node *OnlineSession, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   onlinesession.Table,
			Columns: onlinesession.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: onlinesession.FieldID,
			},
		},
	}
	id, ok := osuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing OnlineSession.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := osuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onlinesession.FieldID)
		for _, f := range fields {
			if !onlinesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != onlinesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := osuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := osuo.mutation.IPAddress(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: onlinesession.FieldIPAddress,
		})
	}
	if value, ok := osuo.mutation.UPid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: onlinesession.FieldUPid,
		})
	}
	_node = &OnlineSession{config: osuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, osuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onlinesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
