// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/mrz-identity-management/ent/onlinesession"
	"github.com/mrzack99s/mrz-identity-management/ent/predicate"
)

// OnlineSessionDelete is the builder for deleting a OnlineSession entity.
type OnlineSessionDelete struct {
	config
	hooks    []Hook
	mutation *OnlineSessionMutation
}

// Where appends a list predicates to the OnlineSessionDelete builder.
func (osd *OnlineSessionDelete) Where(ps ...predicate.OnlineSession) *OnlineSessionDelete {
	osd.mutation.Where(ps...)
	return osd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (osd *OnlineSessionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(osd.hooks) == 0 {
		affected, err = osd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OnlineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			osd.mutation = mutation
			affected, err = osd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(osd.hooks) - 1; i >= 0; i-- {
			if osd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = osd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, osd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (osd *OnlineSessionDelete) ExecX(ctx context.Context) int {
	n, err := osd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (osd *OnlineSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: onlinesession.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: onlinesession.FieldID,
			},
		},
	}
	if ps := osd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, osd.driver, _spec)
}

// OnlineSessionDeleteOne is the builder for deleting a single OnlineSession entity.
type OnlineSessionDeleteOne struct {
	osd *OnlineSessionDelete
}

// Exec executes the deletion query.
func (osdo *OnlineSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := osdo.osd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{onlinesession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (osdo *OnlineSessionDeleteOne) ExecX(ctx context.Context) {
	osdo.osd.ExecX(ctx)
}
