// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/mrz-identity-management/ent/groups"
	"github.com/mrzack99s/mrz-identity-management/ent/predicate"
	"github.com/mrzack99s/mrz-identity-management/ent/users"
)

// UsersUpdate is the builder for updating Users entities.
type UsersUpdate struct {
	config
	hooks    []Hook
	mutation *UsersMutation
}

// Where appends a list predicates to the UsersUpdate builder.
func (uu *UsersUpdate) Where(ps ...predicate.Users) *UsersUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUPid sets the "u_pid" field.
func (uu *UsersUpdate) SetUPid(s string) *UsersUpdate {
	uu.mutation.SetUPid(s)
	return uu
}

// SetUOrgid sets the "u_orgid" field.
func (uu *UsersUpdate) SetUOrgid(s string) *UsersUpdate {
	uu.mutation.SetUOrgid(s)
	return uu
}

// SetUFirstName sets the "u_first_name" field.
func (uu *UsersUpdate) SetUFirstName(s string) *UsersUpdate {
	uu.mutation.SetUFirstName(s)
	return uu
}

// SetULastName sets the "u_last_name" field.
func (uu *UsersUpdate) SetULastName(s string) *UsersUpdate {
	uu.mutation.SetULastName(s)
	return uu
}

// SetUIsActive sets the "u_is_active" field.
func (uu *UsersUpdate) SetUIsActive(b bool) *UsersUpdate {
	uu.mutation.SetUIsActive(b)
	return uu
}

// SetNillableUIsActive sets the "u_is_active" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableUIsActive(b *bool) *UsersUpdate {
	if b != nil {
		uu.SetUIsActive(*b)
	}
	return uu
}

// SetUPasswordUpdatedAt sets the "u_password_updated_at" field.
func (uu *UsersUpdate) SetUPasswordUpdatedAt(t time.Time) *UsersUpdate {
	uu.mutation.SetUPasswordUpdatedAt(t)
	return uu
}

// SetNillableUPasswordUpdatedAt sets the "u_password_updated_at" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableUPasswordUpdatedAt(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetUPasswordUpdatedAt(*t)
	}
	return uu
}

// ClearUPasswordUpdatedAt clears the value of the "u_password_updated_at" field.
func (uu *UsersUpdate) ClearUPasswordUpdatedAt() *UsersUpdate {
	uu.mutation.ClearUPasswordUpdatedAt()
	return uu
}

// SetUExpiredAt sets the "u_expired_at" field.
func (uu *UsersUpdate) SetUExpiredAt(t time.Time) *UsersUpdate {
	uu.mutation.SetUExpiredAt(t)
	return uu
}

// SetNillableUExpiredAt sets the "u_expired_at" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableUExpiredAt(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetUExpiredAt(*t)
	}
	return uu
}

// ClearUExpiredAt clears the value of the "u_expired_at" field.
func (uu *UsersUpdate) ClearUExpiredAt() *UsersUpdate {
	uu.mutation.ClearUExpiredAt()
	return uu
}

// SetInGroupID sets the "in_group" edge to the Groups entity by ID.
func (uu *UsersUpdate) SetInGroupID(id int) *UsersUpdate {
	uu.mutation.SetInGroupID(id)
	return uu
}

// SetNillableInGroupID sets the "in_group" edge to the Groups entity by ID if the given value is not nil.
func (uu *UsersUpdate) SetNillableInGroupID(id *int) *UsersUpdate {
	if id != nil {
		uu = uu.SetInGroupID(*id)
	}
	return uu
}

// SetInGroup sets the "in_group" edge to the Groups entity.
func (uu *UsersUpdate) SetInGroup(g *Groups) *UsersUpdate {
	return uu.SetInGroupID(g.ID)
}

// Mutation returns the UsersMutation object of the builder.
func (uu *UsersUpdate) Mutation() *UsersMutation {
	return uu.mutation
}

// ClearInGroup clears the "in_group" edge to the Groups entity.
func (uu *UsersUpdate) ClearInGroup() *UsersUpdate {
	uu.mutation.ClearInGroup()
	return uu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UsersUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uu.hooks) == 0 {
		if err = uu.check(); err != nil {
			return 0, err
		}
		affected, err = uu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UsersMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uu.check(); err != nil {
				return 0, err
			}
			uu.mutation = mutation
			affected, err = uu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uu.hooks) - 1; i >= 0; i-- {
			if uu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UsersUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UsersUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UsersUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UsersUpdate) check() error {
	if v, ok := uu.mutation.UPid(); ok {
		if err := users.UPidValidator(v); err != nil {
			return &ValidationError{Name: "u_pid", err: fmt.Errorf("ent: validator failed for field \"u_pid\": %w", err)}
		}
	}
	if v, ok := uu.mutation.UOrgid(); ok {
		if err := users.UOrgidValidator(v); err != nil {
			return &ValidationError{Name: "u_orgid", err: fmt.Errorf("ent: validator failed for field \"u_orgid\": %w", err)}
		}
	}
	if v, ok := uu.mutation.UFirstName(); ok {
		if err := users.UFirstNameValidator(v); err != nil {
			return &ValidationError{Name: "u_first_name", err: fmt.Errorf("ent: validator failed for field \"u_first_name\": %w", err)}
		}
	}
	if v, ok := uu.mutation.ULastName(); ok {
		if err := users.ULastNameValidator(v); err != nil {
			return &ValidationError{Name: "u_last_name", err: fmt.Errorf("ent: validator failed for field \"u_last_name\": %w", err)}
		}
	}
	return nil
}

func (uu *UsersUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   users.Table,
			Columns: users.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: users.FieldID,
			},
		},
	}
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.UPid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldUPid,
		})
	}
	if value, ok := uu.mutation.UOrgid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldUOrgid,
		})
	}
	if value, ok := uu.mutation.UFirstName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldUFirstName,
		})
	}
	if value, ok := uu.mutation.ULastName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldULastName,
		})
	}
	if value, ok := uu.mutation.UIsActive(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: users.FieldUIsActive,
		})
	}
	if uu.mutation.UCreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: users.FieldUCreatedAt,
		})
	}
	if value, ok := uu.mutation.UPasswordUpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: users.FieldUPasswordUpdatedAt,
		})
	}
	if uu.mutation.UPasswordUpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: users.FieldUPasswordUpdatedAt,
		})
	}
	if value, ok := uu.mutation.UExpiredAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: users.FieldUExpiredAt,
		})
	}
	if uu.mutation.UExpiredAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: users.FieldUExpiredAt,
		})
	}
	if uu.mutation.InGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   users.InGroupTable,
			Columns: []string{users.InGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: groups.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.InGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   users.InGroupTable,
			Columns: []string{users.InGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: groups.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// UsersUpdateOne is the builder for updating a single Users entity.
type UsersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsersMutation
}

// SetUPid sets the "u_pid" field.
func (uuo *UsersUpdateOne) SetUPid(s string) *UsersUpdateOne {
	uuo.mutation.SetUPid(s)
	return uuo
}

// SetUOrgid sets the "u_orgid" field.
func (uuo *UsersUpdateOne) SetUOrgid(s string) *UsersUpdateOne {
	uuo.mutation.SetUOrgid(s)
	return uuo
}

// SetUFirstName sets the "u_first_name" field.
func (uuo *UsersUpdateOne) SetUFirstName(s string) *UsersUpdateOne {
	uuo.mutation.SetUFirstName(s)
	return uuo
}

// SetULastName sets the "u_last_name" field.
func (uuo *UsersUpdateOne) SetULastName(s string) *UsersUpdateOne {
	uuo.mutation.SetULastName(s)
	return uuo
}

// SetUIsActive sets the "u_is_active" field.
func (uuo *UsersUpdateOne) SetUIsActive(b bool) *UsersUpdateOne {
	uuo.mutation.SetUIsActive(b)
	return uuo
}

// SetNillableUIsActive sets the "u_is_active" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableUIsActive(b *bool) *UsersUpdateOne {
	if b != nil {
		uuo.SetUIsActive(*b)
	}
	return uuo
}

// SetUPasswordUpdatedAt sets the "u_password_updated_at" field.
func (uuo *UsersUpdateOne) SetUPasswordUpdatedAt(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetUPasswordUpdatedAt(t)
	return uuo
}

// SetNillableUPasswordUpdatedAt sets the "u_password_updated_at" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableUPasswordUpdatedAt(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetUPasswordUpdatedAt(*t)
	}
	return uuo
}

// ClearUPasswordUpdatedAt clears the value of the "u_password_updated_at" field.
func (uuo *UsersUpdateOne) ClearUPasswordUpdatedAt() *UsersUpdateOne {
	uuo.mutation.ClearUPasswordUpdatedAt()
	return uuo
}

// SetUExpiredAt sets the "u_expired_at" field.
func (uuo *UsersUpdateOne) SetUExpiredAt(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetUExpiredAt(t)
	return uuo
}

// SetNillableUExpiredAt sets the "u_expired_at" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableUExpiredAt(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetUExpiredAt(*t)
	}
	return uuo
}

// ClearUExpiredAt clears the value of the "u_expired_at" field.
func (uuo *UsersUpdateOne) ClearUExpiredAt() *UsersUpdateOne {
	uuo.mutation.ClearUExpiredAt()
	return uuo
}

// SetInGroupID sets the "in_group" edge to the Groups entity by ID.
func (uuo *UsersUpdateOne) SetInGroupID(id int) *UsersUpdateOne {
	uuo.mutation.SetInGroupID(id)
	return uuo
}

// SetNillableInGroupID sets the "in_group" edge to the Groups entity by ID if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableInGroupID(id *int) *UsersUpdateOne {
	if id != nil {
		uuo = uuo.SetInGroupID(*id)
	}
	return uuo
}

// SetInGroup sets the "in_group" edge to the Groups entity.
func (uuo *UsersUpdateOne) SetInGroup(g *Groups) *UsersUpdateOne {
	return uuo.SetInGroupID(g.ID)
}

// Mutation returns the UsersMutation object of the builder.
func (uuo *UsersUpdateOne) Mutation() *UsersMutation {
	return uuo.mutation
}

// ClearInGroup clears the "in_group" edge to the Groups entity.
func (uuo *UsersUpdateOne) ClearInGroup() *UsersUpdateOne {
	uuo.mutation.ClearInGroup()
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UsersUpdateOne) Select(field string, fields ...string) *UsersUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated Users entity.
func (uuo *UsersUpdateOne) Save(ctx context.Context) (*Users, error) {
	var (
		err  error
		node *Users
	)
	if len(uuo.hooks) == 0 {
		if err = uuo.check(); err != nil {
			return nil, err
		}
		node, err = uuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UsersMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uuo.check(); err != nil {
				return nil, err
			}
			uuo.mutation = mutation
			node, err = uuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuo.hooks) - 1; i >= 0; i-- {
			if uuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UsersUpdateOne) SaveX(ctx context.Context) *Users {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UsersUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UsersUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UsersUpdateOne) check() error {
	if v, ok := uuo.mutation.UPid(); ok {
		if err := users.UPidValidator(v); err != nil {
			return &ValidationError{Name: "u_pid", err: fmt.Errorf("ent: validator failed for field \"u_pid\": %w", err)}
		}
	}
	if v, ok := uuo.mutation.UOrgid(); ok {
		if err := users.UOrgidValidator(v); err != nil {
			return &ValidationError{Name: "u_orgid", err: fmt.Errorf("ent: validator failed for field \"u_orgid\": %w", err)}
		}
	}
	if v, ok := uuo.mutation.UFirstName(); ok {
		if err := users.UFirstNameValidator(v); err != nil {
			return &ValidationError{Name: "u_first_name", err: fmt.Errorf("ent: validator failed for field \"u_first_name\": %w", err)}
		}
	}
	if v, ok := uuo.mutation.ULastName(); ok {
		if err := users.ULastNameValidator(v); err != nil {
			return &ValidationError{Name: "u_last_name", err: fmt.Errorf("ent: validator failed for field \"u_last_name\": %w", err)}
		}
	}
	return nil
}

func (uuo *UsersUpdateOne) sqlSave(ctx context.Context) (_node *Users, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   users.Table,
			Columns: users.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: users.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Users.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, users.FieldID)
		for _, f := range fields {
			if !users.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != users.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.UPid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldUPid,
		})
	}
	if value, ok := uuo.mutation.UOrgid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldUOrgid,
		})
	}
	if value, ok := uuo.mutation.UFirstName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldUFirstName,
		})
	}
	if value, ok := uuo.mutation.ULastName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: users.FieldULastName,
		})
	}
	if value, ok := uuo.mutation.UIsActive(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: users.FieldUIsActive,
		})
	}
	if uuo.mutation.UCreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: users.FieldUCreatedAt,
		})
	}
	if value, ok := uuo.mutation.UPasswordUpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: users.FieldUPasswordUpdatedAt,
		})
	}
	if uuo.mutation.UPasswordUpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: users.FieldUPasswordUpdatedAt,
		})
	}
	if value, ok := uuo.mutation.UExpiredAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: users.FieldUExpiredAt,
		})
	}
	if uuo.mutation.UExpiredAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: users.FieldUExpiredAt,
		})
	}
	if uuo.mutation.InGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   users.InGroupTable,
			Columns: []string{users.InGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: groups.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.InGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   users.InGroupTable,
			Columns: []string{users.InGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: groups.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Users{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
