// Code generated by entc, DO NOT EDIT.

package groupbandwidth

import (
	"time"
)

const (
	// Label holds the string label denoting the groupbandwidth type in the database.
	Label = "group_bandwidth"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGbwDownloadSpeed holds the string denoting the gbw_download_speed field in the database.
	FieldGbwDownloadSpeed = "gbw_download_speed"
	// FieldGbwUploadSpeed holds the string denoting the gbw_upload_speed field in the database.
	FieldGbwUploadSpeed = "gbw_upload_speed"
	// FieldGbwCreatedAt holds the string denoting the gbw_created_at field in the database.
	FieldGbwCreatedAt = "gbw_created_at"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the groupbandwidth in the database.
	Table = "group_bandwidths"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "groups"
	// GroupsInverseTable is the table name for the Groups entity.
	// It exists in this package in order to avoid circular dependency with the "groups" package.
	GroupsInverseTable = "groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "group_bandwidth_groups"
)

// Columns holds all SQL columns for groupbandwidth fields.
var Columns = []string{
	FieldID,
	FieldGbwDownloadSpeed,
	FieldGbwUploadSpeed,
	FieldGbwCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGbwCreatedAt holds the default value on creation for the "gbw_created_at" field.
	DefaultGbwCreatedAt func() time.Time
)
