// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GroupBandwidth is the predicate function for groupbandwidth builders.
type GroupBandwidth func(*sql.Selector)

// Groups is the predicate function for groups builders.
type Groups func(*sql.Selector)

// OnlineSession is the predicate function for onlinesession builders.
type OnlineSession func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
